player.onChat("tp", function () {
    agent.teleportToPlayer()
})
player.onChat("speed", function () {
    agent.setItem(PLANKS_OAK, 1, 1)
    agent.move(DOWN, 5)
    agent.setAssist(PLACE_ON_MOVE, true)
    for (let index = 0; index < 5; index++) {
        agent.move(BACK, 10)
        agent.move(LEFT, 1)
        agent.move(FORWARD, 10)
        agent.move(LEFT, 1)
    }
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(UP, 1)
    agent.move(RIGHT, 1)
    agent.setAssist(PLACE_ON_MOVE, true)
    for (let index = 0; index < 3; index++) {
        agent.move(BACK, 10)
        agent.move(UP, 1)
        agent.move(FORWARD, 10)
        agent.move(UP, 1)
    }
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(RIGHT, 9)
    agent.move(DOWN, 6)
    agent.setAssist(PLACE_ON_MOVE, true)
    for (let index = 0; index < 3; index++) {
        agent.move(BACK, 10)
        agent.move(UP, 1)
        agent.move(FORWARD, 10)
        agent.move(UP, 1)
    }
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(LEFT, 1)
    agent.move(DOWN, 6)
    agent.setAssist(PLACE_ON_MOVE, true)
    for (let index = 0; index < 3; index++) {
        agent.move(LEFT, 8)
        agent.move(UP, 1)
        agent.move(RIGHT, 10)
        agent.move(UP, 1)
    }
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(BACK, 1)
    agent.move(DOWN, 1)
    agent.setAssist(PLACE_ON_MOVE, true)
    for (let index = 0; index < 4; index++) {
        agent.move(BACK, 9)
        agent.move(LEFT, 1)
        agent.move(FORWARD, 9)
        agent.move(LEFT, 1)
    }
    agent.move(DOWN, 1)
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(BACK, 9)
    agent.setAssist(PLACE_ON_MOVE, true)
    agent.move(DOWN, 4)
    agent.move(RIGHT, 1)
    agent.move(UP, 4)
    agent.move(RIGHT, 1)
    agent.move(DOWN, 4)
    agent.move(RIGHT, 1)
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(UP, 2)
    agent.setAssist(PLACE_ON_MOVE, true)
    agent.move(UP, 2)
    agent.move(RIGHT, 1)
    agent.move(DOWN, 2)
    agent.move(RIGHT, 1)
    agent.setAssist(PLACE_ON_MOVE, false)
    agent.move(DOWN, 2)
    agent.setAssist(PLACE_ON_MOVE, true)
    agent.move(UP, 4)
    agent.move(RIGHT, 1)
    agent.move(DOWN, 4)
    agent.move(RIGHT, 1)
    agent.move(UP, 4)
    agent.move(BACK, 1)
    agent.setAssist(PLACE_ON_MOVE, false)
})
